spring:
  thymeleaf:
    cache: false
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/tmp/springbootPersonList
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update